### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by zw963**
refactor and fix some special issue.

### CODE REVIEW

**Comment by zw963** [comment]
```sh
The command "eval bundle install --jobs=3 --retry=3 " failed 3 times.

The command "bundle install --jobs=3 --retry=3" failed and exited with 6 during .

Your build has been stopped.
```

failed seem like not caused by my PR ?

**Comment by iliabylich** [comment]
I've restarted a job, but it still fails. Could you change a travis matrix? I think we can remove old versions of MRI from the build matrix. `ruby-lang.org` says that `2.2.7` is the latest supported Ruby version. You can leave `2.2.0`, `2.3.0` and `2.4.0` in `.travis.yml`, I hope it may help.

Anyway, travis says that the build is green on `2.0.0` and `2.2.0`, I'd like to merge it, 👍 .

**Comment by zw963** [comment]
Passed !  : )

**Comment by zw963** [comment]
I want to use this gem in my production.

when some special exception happen, we want wo persistance those
summary infomation to redis, and with some easy to trace with rails log
key name.

Does you have some special advice about this?

I think this gem will help our a lot. thanks

**Comment by iliabylich** [comment]
@zw963 I don't think that this gem is good for production. [These lines](https://github.com/iliabylich/exception_manager/blob/master/lib/exception_manager/config.rb#L20-L26) do the main job, the gem works on the thing called TracePoint, as I know it affects overall Ruby performance.
Of course you could try it yourself, maybe your app has enough extra capacity.

**Pull request merged**
